export default {
  cn: {
    // b s
    homeWelcome: '欢迎页',
    home: '首页',
    detail: '天使系列详情页',
    customized: '定制天使熊猫',
    customizedResult: '定制结果',
    userPanda: '我的熊猫',
    userOrder: '我的账单',
    userOrderDetail: '订单详情',
    userOrderExpress: '订单物流',
    userMessage: '我的消息',
    userAssets: '我的资产',
    userSetting: '设置',
    pandaDetail: '熊猫详情',
    explore: '探索',
    market: '交易市场',
    marketList: '交易市场系列',
    marketIntro: '交易市场介绍',
    marketSell: '出售',
    breedingMarket: '繁殖市场',
    breedingPrediction: '繁殖预测',
    breedingMarketIntro: '繁殖介绍',
    breedingMarketError: '繁殖错误',
    breedingBuy: '繁殖购买',
    buyNow: '完成订单',
    buyPay: '支付',
    paySuccess: '支付成功',
    payError: '支付失败',
    marketSellBuy: '购买/出价',
    marketCallback: '支付信息',
    marketDetail: '详情',
    marketPickUpGoods: '提货',
    searchPandas: '搜索熊猫',

    // b end
    phoneLogin: '登录 | Panda Earth',
    emailLogin: '邮箱登录 | Panda Earth',
    redirect: '微信登录 | Panda Earth',
    selectArea: '选择国家/地区 | Panda Earth',
    enterPassword: '输入密码 | Panda Earth',
    resetPassword: '重置密码 | Panda Earth',
    enterSafeCode: '输入验证码 | Panda Earth',
    setPassword: '设置密码 | Panda Earth',
    bindPhone: '绑定手机号 | Panda Earth',
    changeAvatar: '修改头像 | Panda Earth',
    changeUsername: '修改用户名 | Panda Earth',
    changePassword: '修改密码 | Panda Earth',
    addressList: '收货信息 | Panda Earth',
    addAddress: '添加地址 | Panda Earth',
    editAddress: '编辑地址 | Panda Earth',
    changePhoneNumber: '修改手机号 | Panda Earth',
    changePhoneSafeCode: '修改手机号 | Panda Earth',
    privacyPolicy: '隐私政策 | Panda Earth',
    accountAndSafe: '账户与安全 | Panda Earth',
    about: '关于 | Panda Earth',
    feedback: '反馈建议 | Panda Earth',
    balance: '账户余额 | Panda Earth',
    topUp: '充值 | Panda Earth',
    withdraw: '提现 | Panda Earth',
    withdrawSuccess: '提现成功 | Panda Earth',
    accountDetails: '账户明细 | Panda Earth',
    editBankCard: '编辑银行卡 | Panda Earth',
    confirmToCash: '确认兑现 | Panda Earth',
    toCashSuccess: '兑现成功 | Panda Earth'
  },
  en: {
    // b s
    homeWelcome: '欢迎页',
    home: '首页',
    detail: '天使系列详情页',
    customized: '定制天使熊猫',
    customizedResult: '定制结果',
    userPanda: '我的熊猫',
    userOrder: '我的账单',
    userOrderDetail: '订单详情',
    userOrderExpress: '订单物流',
    userMessage: '我的消息',
    userAssets: '我的资产',
    userSetting: '设置',
    pandaDetail: '熊猫详情',
    explore: '探索',
    market: '交易市场',
    marketList: '交易市场系列',
    marketIntro: '交易市场介绍',
    marketSell: '出售',
    breedingMarket: '繁殖市场',
    breedingPrediction: '繁殖预测',
    breedingMarketIntro: '繁殖介绍',
    breedingMarketError: '繁殖错误',
    breedingBuy: '繁殖购买',
    buyNow: '完成订单',
    buyPay: '支付',
    paySuccess: '支付成功',
    payError: '支付失败',
    marketSellBuy: '购买/出价',
    marketCallback: '支付信息',
    marketDetail: '详情',
    marketPickUpGoods: '提货',
    searchPandas: '搜索熊猫',
    // b end
    phoneLogin: '登录 | Panda Earth',
    emailLogin: '邮箱登录 | Panda Earth',
    redirect: '微信登录 | Panda Earth',
    selectArea: 'Select country or region | Panda Earth',
    enterPassword: 'Enter your password | Panda Earth',
    resetPassword: 'Reset your password | Panda Earth',
    enterSafeCode: 'Enter your dial code | Panda Earth',
    setPassword: 'Set your Password | Panda Earth',
    bindPhone: 'Bind your phone | Panda Earth',
    replaceAvatar: 'Change avatar | Panda Earth',
    changeUsername: 'Change user name | Panda Earth',
    changePassword: 'Change your password | Panda Earth',
    addressList: 'Your receipt information | Panda Earth',
    addAddress: '添加地址 | Panda Earth',
    editAddress: '编辑地址 | Panda Earth',
    changePhoneNumber: 'Change your phone number | Panda Earth',
    privacyPolicy: 'Privacy policy | Panda Earth',
    accountAndSafe: '账户与安全 | Panda Earth',
    about: '关于 | Panda Earth',
    feedback: '反馈建议 | Panda Earth',
    balance: '账户余额 | Panda Earth',
    topUp: '充值 | Panda Earth',
    withdraw: '提现 | Panda Earth',
    withdrawSuccess: '提现成功 | Panda Earth',
    accountDetails: '账户明细 | Panda Earth',
    editBankAccount: '编辑银行卡 | Panda Earth',
    confirmToCash: '确认兑现 | Panda Earth',
    toCashSuccess: '兑现成功 | Panda Earth'
  }
}