export const SET_SAFE_CODE = 'SET_SAFE_CODE'

// login
export const SET_WX_USER_INFO = 'SET_WX_USER_INFO'
export const SET_USER_STATUS = 'SET_USER_STATUS'

// user
export const SET_USER_INFO = 'SET_USER_INFO'

// jssdk
export const GET_JSSDK_INFO = 'GET_JSSDK_INFO'

// address
export const SET_ADDRESS_INFO = 'SET_ADDRESS_INFO'
export const RESET_ADDRESS_INFO = 'RESET_ADDRESS_INFO'
export const SET_DEFAULT_ADDRESS_INFO = 'SET_DEFAULT_ADDRESS_INFO'
export const RESET_ADDRESS_LIST = 'RESET_ADDRESS_LIST'
export const RESET_DEFAULT_ADDRESS_INFO = 'RESET_DEFAULT_ADDRESS_INFO'

// message
export const GET_MESSAGE_MAXID = 'GET_MESSAGE_MAXID'
export const GET_MESSAGE_ISNEW = 'GET_MESSAGE_ISNEW'

// notification
export const RESET_NOTIFICATION_ARR = 'RESET_NOTIFICATION_ARR'
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const SHIFT_NOTIFICATION = 'SHIFT_NOTIFICATION'

// selectArea
export const SET_AREA_INFO = 'SET_AREA_INFO'
export const SET_SHOW_SELECT_AREA_STATUS = 'SET_SHOW_SELECT_AREA_STATUS'
export const RESET_AREA_INFO = 'RESET_AREA_INFO'

// addressList
export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST'
export const SET_EDIT_ADDRESS_INFO = 'SET_EDIT_ADDRESS_INFO'

// changeAvatar
export const SET_URL = 'SET_URL'
export const SET_IMAGE_PATH = 'SET_IMAGE_PATH'
export const SET_AVATAR_CHANGE_STATUS = 'SET_AVATAR_CHANGE_STATUS'

// CUSTOMIZED
export const SET_CUSTOMIZED_INFO = 'SET_CUSTOMIZED_INFO'
export const RESET_CUSTOMIZED_INFO = 'RESET_CUSTOMIZED_INFO'